version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: org.hibernate.validator:hibernate-validator
        versions:
          - "> 7.x.x.Final"
      - dependency-name: jakarta.el:jakarta.el-api
        versions:
          - "> 4.x.x"
      - dependency-name: jakarta.xml.bind:jakarta.xml.bind-api
        versions:
          - "> 3.x.x"
      - dependency-name: com.sun.xml.bind:jaxb-impl
        versions:
          - "> 2.4.x"
      - dependency-name: jakarta.annotation:jakarta.annotation-api
        versions:
          - "> 2.x.x"
      - dependency-name: com.sun.xml.bind:jaxb-core
        versions:
          - "> 3.x.x"

